### ISSUE TITLE
Q: Best representation for a structure

### ISSUE THREAD

**Issue by jlkiri** [tailhook/knuffel#10]
Hi, awesome library but I'm struggling with representing a rather freestyle structure like this:

```kdl
genres {
    rock
    metal
    pop {
         albums-by-year {
             y2000 "a" "b" "c"
             y2001 "d" "e"    
         }
    }
}
```

Here, for example I expect there to be a top-level `genres` node but I don't restrict which and how many child nodes it has. Then each node again is expected to have smth like `albums-by-year` which itself is again pretty freestyle key-value table. How can I do this with `knuffel`? I expect to be able to do smth like this:

```rust
#[derive(Debug, knuffel::Decode)]
struct Genre {
    #[knuffel(node_name)]
    node_name: String // name of the genre
    #[knuffel(children)]
    info: Option<Info>
}
```

```rust
#[derive(Debug, knuffel::Decode)]
struct Genres {
    #[knuffel(children)]
    genres: Vec<Genre>,
}
```

**Comment by tailhook** [comment]
Yes. Sounds like you can. Note if you need free-form things somewhere you can even embed `knuffel::ast::Node` anywhere, that would capture arbitrary inner structure.
