### ISSUE TITLE
Expects `DecodeScalar` for `f32`

### ISSUE THREAD

**Issue by spikespaz** [tailhook/knuffel#5]
Given the following:
```rust
#[derive(Clone, Debug, knuffel::Decode)]
pub struct ManifestNode {
    #[knuffel(child, unwrap(argument))]
    pub version: f32,
}
```

`cargo check`

```
error[E0277]: the trait bound `f32: DecodeScalar<S>` is not satisfied
 --> backend/src/manifest.rs:9:24
  |
9 | #[derive(Clone, Debug, knuffel::Decode)]
  |                        ^^^^^^^^^^^^^^^ the trait `DecodeScalar<S>` is not implemented for `f32`
```

Why is this?

**Comment by tailhook** [comment]
Looks like was just never implemented. Do you want to contribute? Should be very similar to what we do for integer types.

**Comment by spikespaz** [comment]
What is that `lib` folder with the empty manifest for?

**Comment by spikespaz** [comment]
In an effort to familiarize myself with the codebase, do you have a problem with me replacing verbose code with [`strum`](https://docs.rs/strum/latest/strum/) macros?

**Comment by tailhook** [comment]
> What is that `lib` folder with the empty manifest for?

That's mistake. *(I didn't know how to make lib at workspace root, so it lived in the lib folder for some time, and then I didn't notice it's there when changing structure)*

> In an effort to familiarize myself with the codebase, do you have a problem with me replacing verbose code with [`strum`](https://docs.rs/strum/latest/strum/) macros? As a separate PR.

I don't think this is needed. This will increase compile times. And also might introduce some tricky backwards compatibility issues. I think this crate should be pretty low maintenance in the core. "Derive" is the most complex part of the crate, but I don't think strum will make it considerably simpler.

**Comment by spikespaz** [comment]
What is this `n(0)`?
```rust
#[cfg_attr(feature="minicbor", n(0))]
```
