### ISSUE TITLE
Can't use enum as single child

### ISSUE THREAD

**Issue by silen-z** [tailhook/knuffel#7]
Given 

```rust
#[derive(Debug, knuffel::Decode)]
struct SomeDocument {
    #[knuffel(child)]
    some_node: SomeEnum,
}

#[derive(Debug, knuffel::Decode)]
enum SomeEnum {
    SomeVariant(SomeVariant),
    AnotherVariant(AnotherVariant),
}

#[derive(Debug, knuffel::Decode)]
struct SomeVariant {}

#[derive(Debug, knuffel::Decode)]
struct AnotherVariant {}
```

if I try to parse

```kdl
some-variant
```
I get errors: "unexpected node `some-variant`" and "child node `some-node` is required"

but if I try to parse
```
some-node
```
I get "expected one of `some-variant`, `another-variant`"

I tried many variations of this in hope that I'm just misunderstanding KDL or knuffel, but in the end I checked the Decode implementations with `cargo expand` and it appears that the node is expected to have name of the parent struct field and one of the enum variants at the same time.

full reproduction here: https://github.com/silen-z/knuffel-enum-bug-repro/blob/main/src/lib.rs

**Comment by rnarkk** [comment]
This is the most important case of #18 where such inconsistency finally cannot hold any longer. When #18 is solved, this becomes as easy as it is:

```rust
#[derive(Debug, Decode)]
struct Document  {
    #[knuffel(child)]
    either: Either,
    ..
}

#[derive(Debug, Decode)]
enum Either {
    One,
    Another,
}
```

**Comment by tailhook** [comment]
Sorry for the long delay.

Well, the core here is that we don't allow positional children (which usually hard to understand for users, I think).

So you either do a catch-all `children` rule:
```
#[derive(Debug, knuffel::Decode)]
struct SomeDocument {
    #[knuffel(children)]
    some_node: Vec<SomeEnum>,
}
```
In this case `some_node` is not present in kdl. Or use multiple children:
```
#[derive(Debug, knuffel::Decode)]
struct SomeDocument {
    #[knuffel(child)]
    some_variant: Option<SomeVariant>,
    #[knuffel(child)]
    other_variant: Option<SomeVariant>,
}
```

**Comment by tailhook** [comment]
So far I think that using either option from the above and tiny post check is good enough solution for use case that looks quite niche. But feel free to provide more details if you think otherwise.

**Comment by tailhook** [comment]
Another thought: Fixing #8, which is a definitely valid request, will open another way to get this task done.
