### ISSUE TITLE
RTL property names don’t work without explicit name?

### ISSUE THREAD

**Issue by Porges** [tailhook/knuffel#9]
I’m not sure why this is happening, but this does not work (resulting in "unexpected property"):

```rs
#[derive(knuffel::Decode)]
pub struct الطاب {
    #[knuffel(property)]
    pub الطاب: i64,
}

```

… but this, with an explicit `name`, does:

```rs
#[derive(knuffel::Decode)]
pub struct الطاب {
    #[knuffel(property(name = "الطاب"))]
    pub الطاب: i64,
}
```

**Comment by tailhook** [comment]
What do you mean by doesn't work? We do case folding of the names. So probably that name have a different representation when case-folded so it doesn't match the property you expect.

If case folding is wrong, you should report the issue into `heck` crate.

Other that that, feel free to reopen the issue providing more details.

**Comment by Porges** [comment]
@tailhook here is a repro.

This works as expected:
```rs
fn main() {
    knuffel::parse::<Vec<Foo>>("example.kdl", r#"foo prop=123"#).unwrap();
}

#[derive(knuffel::Decode)]
pub struct Foo {
    #[knuffel(property)]
    pub prop: i64,
}
```

This works (node with RTL name):
```rs
fn main() {
    knuffel::parse::<Vec<الطاب>>("example.kdl", r#"الطاب prop=123"#).unwrap();
}

#[derive(knuffel::Decode)]
pub struct الطاب {
    #[knuffel(property)]
    pub prop: i64,
}
```

This doesn't work (property with RTL name):
```rs
fn main() {
    knuffel::parse::<Vec<Foo>>("example.kdl", r#"foo الطاب=123"#).unwrap();
}

#[derive(knuffel::Decode)]
pub struct Foo {
    #[knuffel(property)]
    pub الطاب: i64,
}
```

The error is:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { source_code: NamedSource { name: "example.kdl", source: "<redacted>", errors: [Diagnostic { message: "unexpected property `\\u{627}\\u{644}\\u{637}\\u{627}\\u{628}`", labels: "[LabeledSpan { label: Some(\"unexpected property\"), span: SourceSpan { offset: SourceOffset(4), length: SourceOffset(10) } }]" }
```

This works (property with RTL name with explicit name set):
```rs
fn main() {
    knuffel::parse::<Vec<Foo>>("example.kdl", r#"foo الطاب=123"#).unwrap();
}

#[derive(knuffel::Decode)]
pub struct Foo {
    #[knuffel(property(name = "الطاب"))]
    pub الطاب: i64,
}
```

Case folding shouldn't be the problem here; Arabic has no case.

**Comment by Porges** [comment]
It looks like `heck` is a bit broken here: `"الطاب".to_kebab_case()` returns the empty string.

**Comment by Porges** [comment]
Actually, this does work properly in `heck` if the `unicode` feature is turned on. `knuffel-derive` might need to expose that.

**Comment by tailhook** [comment]
Oh, sure. Let's enable the feature.
